app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'
urlpatterns = [
    path('', views.create_sesikonsultasi, name='create_sesikonsultasi'),
    path('daftar_sesi_konsultasi', views.daftar_sesikonsultasi, name='daftar_sesikonsultasi'),
    path('update_sesi_konsultasi', views.update_sesikonsultasi, name='update_sesikonsultasi'),
    path('delete_sesi_konsultasi', views.delete_sesikonsultasi, name='delete_sesikonsultasi'),
    path('create_rs_cabang',views.create_rs_cabang, name='create_rs_cabang'),
    path('daftar_rs_cabang', views.daftar_rs_cabang, name='daftar_rs_cabang'),
    path('update_rs_cabang', views.update_rs_cabang, name='update_rs_cabang'),
    path('delete_rs_cabang', views.delete_rs_cabang, name= 'delete_rs_cabang'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('signup/admin',views.signup_admin, name='signup_admin'),
    path('signup/dokter',views.signup_dokter, name='signup_dokter'),
    path('signup/pasien',views.signup_pasien, name='signup_pasien'),
    path('auth', views.auth, name='auth'),
    path('logout', views.logout, name='logout'),
    path('admin', views.admin, name='admin'),
    path('pengguna', views.pengguna, name='pengguna'),
]

medikago_b5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
    path('app4/', include('app4.urls')),
    path('app5/', include('app5.urls')),
]

templates/header/footer.html
<div class="bg-dark py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-8 my-1">
                <div class="footer-copyright text-center py-3">© 2020 Copyright: MedikaGoB5</div>
            </div>
        </div>
    </div>
</div>

templates/header/header.html
{% load static %}

<nav style="background-color: #F1DED0;" class="navbar navbar-expand-md navbar-dark" >
    <div class="container" style="position:static;">
      <a style="color: #222831;" class="navbar-brand" href="/">
        <i class="fa d-inline fa-lg fa-database"></i>
        <b>MedikaGo</b>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="nav navbar-nav navbar-right">

        {% if request.session.user == "nothing" %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login:home' %}">Login</a>
          </li>
        {% elif request.session.user == "administrator" %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'login:admin' %}"><img src="{% static 'img/user.png' %}" style="width:30px; display:inline;"></a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login:pengguna' %}"><img src="{% static 'img/user.png' %}" style="width:30px; display:inline;"></a>
          </li>
        {% endif %}
          

      </ul>
  </div>

</nav>
 