app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'
urlpatterns = [
    path('', views.create_sesikonsultasi, name='create_sesikonsultasi'),
    path('daftar_sesi_konsultasi', views.daftar_sesikonsultasi, name='daftar_sesikonsultasi'),
    path('update_sesi_konsultasi', views.update_sesikonsultasi, name='update_sesikonsultasi'),
    path('delete_sesi_konsultasi', views.delete_sesikonsultasi, name='delete_sesikonsultasi'),
    path('create_rs_cabang',views.create_rs_cabang, name='create_rs_cabang'),
    path('daftar_rs_cabang', views.daftar_rs_cabang, name='daftar_rs_cabang'),
    path('update_rs_cabang', views.update_rs_cabang, name='update_rs_cabang'),
    path('delete_rs_cabang', views.delete_rs_cabang, name= 'delete_rs_cabang'),
]

app2/urls.py
from django.urls import path
from . import views

app_name = 'app2'

urlpatterns = [
	path('profil', views.profil, name='profil'),
	path('create_tindakan_poli', views.create_tindakan_poli, name='create_tindakan_poli'),
    path('view_daftar_tindakan_poli', views.view_daftar_tindakan_poli, name='view_daftar_tindakan_poli'),
    path('update_tindakan_poli', views.update_tindakan_poli, name='update_tindakan_poli'),
    path('delete_tindakan_poli', views.delete_tindakan_poli, name='delete_tindakan_poli'),
	path('create_tindakan', views.create_tindakan, name='create_tindakan'),
    path('view_daftar_tindakan', views.view_daftar_tindakan, name='view_daftar_tindakan'),
    path('update_tindakan', views.update_tindakan, name='update_tindakan'),
    path('delete_tindakan', views.delete_tindakan, name='delete_tindakan'),
]

app4/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from .views import *
from . import views

app_name = 'app4'

urlpatterns = [
    path('create_dokter_rs_cabang', create_dokter_rs_cabang, name='create_dokter_rs_cabang'),
    path('daftar_dokter_rs_cabang', daftar_dokter_rs_cabang, name='daftar_dokter_rs_cabang'),
    path('update_dokter_rs_cabang', update_dokter_rs_cabang, name='update_dokter_rs_cabang'),
    path('delete_dokter_rs_cabang', delete_dokter_rs_cabang, name='delete_dokter_rs_cabang'),

    path('create_layanan_poliklinik', create_layanan_poliklinik, name='create_layanan_poliklinik'),
    path('daftar_layanan_poliklinik', daftar_layanan_poliklinik, name='daftar_layanan_poliklinik'),
    path('update_layanan_poliklinik/<id>/', update_layanan_poliklinik, name='update_layanan_poliklinik'),
    path('delete_layanan_poliklinik/<id>/', delete_layanan_poliklinik, name='delete_layanan_poliklinik'),

    path('daftar_jadwal_poliklinik', daftar_jadwal_poliklinik, name='daftar_jadwal_poliklinik'),
    path('daftar_jadwal_poliklinik/<id>/', daftar_jadwal_poliklinik_khusus, name='daftar_jadwal_poliklinik'),
    path('update_jadwal_poliklinik/<id>/', update_jadwal_poliklinik, name='update_jadwal_poliklinik'),
    path('delete_jadwal_poliklinik/<id>/', delete_jadwal_poliklinik, name='delete_jadwal_poliklinik'),

]

app5/urls.py
from django.urls import path
from . import views

app_name = 'app5'
urlpatterns = [
    path('', views.create_transaksi, name='create_transaksi'),
    path('daftar_transaksi', views.daftar_transaksi, name='daftar_transaksi'),
    path('update_transaksi', views.update_transaksi, name='update_transaksi'),
    path('delete_transaksi', views.delete_transaksi, name='delete_transaksi'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('signup/admin',views.signup_admin, name='signup_admin'),
    path('signup/dokter',views.signup_dokter, name='signup_dokter'),
    path('signup/pasien',views.signup_pasien, name='signup_pasien'),
    path('auth', views.auth, name='auth'),
    path('logout', views.logout, name='logout'),
    path('admin', views.admin, name='admin'),
    path('pengguna', views.pengguna, name='pengguna'),
]

medikago_b5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
    path('app4/', include('app4.urls')),
    path('app5/', include('app5.urls')),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms


class SignUpAdminForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
        'type' : 'text',
        'required': True,
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'type' : 'password',
        'placeholder': 'Password',
        'required': True,
    }))

    nomor_identitas = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nomor Identitas',
        'type' : 'text',
        'required': True,
    }))

    nama_lengkap = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Lengkap',
        'type' : 'text',
        'required': True,
    }))


    tanggal_lahir = forms.DateField(input_formats=['%Y-%m-%d'],widget=forms.widgets.DateInput(attrs={
    'class': 'form-control',
    'placeholder': 'Tanggal Lahir',
    'type': 'date',
    'required': True,
    }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        'type' : 'text',
        'required': True,
    }))

    alamat = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Alamat',
        'type' : 'text',
        'required': True,
    }))

class SignUpDokterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
        'type' : 'text',
        'required': True,
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'type' : 'password',
        'placeholder': 'Password',
        'required': True,
    }))

    nomor_identitas = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nomor Identitas',
        'type' : 'text',
        'required': True,
    }))

    nama_lengkap = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Lengkap',
        'type' : 'text',
        'required': True,
    }))


    tanggal_lahir = forms.DateField(input_formats=['%Y-%m-%d'],widget=forms.widgets.DateInput(attrs={
    'class': 'form-control',
    'placeholder': 'Tanggal Lahir',
    'type': 'date',
    'required': True,
    }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        'type' : 'text',
        'required': True,
    }))

    alamat = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Alamat',
        'type' : 'text',
        'required': True,
    }))

    no_sip = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'No SIP',
        'type' : 'text',
        'required': True,
    }))

    spesialisasi = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Spesialisasi',
        'type' : 'text',
        'required': True,
    }))


class SignUpPasienForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
        'type' : 'text',
        'required': True,
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'type' : 'password',
        'placeholder': 'Password',
        'required': True,
    }))

    nomor_identitas = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nomor Identitas',
        'type' : 'text',
        'required': True,
    }))

    nama_lengkap = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Lengkap',
        'type' : 'text',
        'required': True,
    }))


    tanggal_lahir = forms.DateField(input_formats=['%Y-%m-%d'],widget=forms.widgets.DateInput(attrs={
    'class': 'form-control',
    'placeholder': 'Tanggal Lahir',
    'type': 'date',
    'required': True,
    }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        'type' : 'text',
        'required': True,
    }))

    alamat = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Alamat',
        'type' : 'text',
        'required': True,
    }))

    alergi = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Alergi',
        'type' : 'text',
        'required': True,
    }))

login/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.db import connection
from .forms import *

import random

# Create your views here.
def home(request):
    try:
        if(request.session["user"]):
            pass
    except:
        request.session["user"] = "nothing"

    return render(request, 'home.html')

def signup(request):
    if(request.method == "GET" and request.session["user"] == "nothing"):
        return render(request,'signup.html')
    return redirect(reverse("login:home"))
       
    

def signup_admin(request):
    if(request.method == "GET" and request.session["user"] == "nothing"):
        signup_admin = SignUpAdminForm()
        response = {
            'admin_form': signup_admin,
        }
        return render(request, 'signup_admin.html', response)
    elif(request.method == "POST" and request.session["user"] == "nothing"):
        cursor = connection.cursor()
        username = request.POST['username']
        password = request.POST['password']
        nomor_identitas = request.POST['nomor_identitas']
        nama_lengkap = request.POST['nama_lengkap']
        tanggal_lahir = request.POST['tanggal_lahir']
        email = request.POST['email']
        alamat = request.POST['alamat']
        
        # Insert to table pengguna
        try:
            cursor.execute(f"INSERT INTO medikago.pengguna (email, username, password, nama_lengkap, nomor_id, tanggal_lahir, alamat) VALUES ('{email}','{username}','{password}', '{nama_lengkap}', '{nomor_identitas}','{tanggal_lahir}', '{alamat}')")
        except:
            messages.error(request, "Data yang anda masukkan salah")
            return redirect(reverse("login:signup_admin"))
        
        # Generate random
        nomor_pegawai = f"{random.randint(0,9999)}"
        
        # Insert to table admin
        # Asumsi kode rs default RSTU
        cursor.execute(f"INSERT INTO medikago.administrator (nomor_pegawai, username, kode_rs) VALUES ('{nomor_pegawai}', '{username}', 'RSTU')")
        
        request.session["user"] = "administrator"
        request.session["id"] = nomor_pegawai

        return redirect(reverse("login:pengguna"))
    return redirect(reverse("login:home"))

def signup_dokter(request):
    if(request.method == "GET" and request.session["user"] == "nothing"): 
        signup_dokter = SignUpDokterForm()
        response = {
            'dokter_form': signup_dokter,
        }
        return render(request, 'signup_dokter.html', response)
    elif(request.method == "POST" and request.session["user"] == "nothing"):
        cursor = connection.cursor()
        username = request.POST['username']
        password = request.POST['password']
        nomor_identitas = request.POST['nomor_identitas']
        nama_lengkap = request.POST['nama_lengkap']
        tanggal_lahir = request.POST['tanggal_lahir']
        email = request.POST['email']
        alamat = request.POST['alamat']
        no_sip = request.POST['no_sip']
        spesialisasi = request.POST['spesialisasi']

        # Insert to table pengguna
        try:
            cursor.execute(f"INSERT INTO medikago.pengguna (email, username, password, nama_lengkap, nomor_id, tanggal_lahir, alamat) VALUES ('{email}','{username}','{password}', '{nama_lengkap}', '{nomor_identitas}','{tanggal_lahir}', '{alamat}')")
        except:
            messages.error(request, "Data yang anda masukkan salah")
            return redirect(reverse("login:signup_dokter"))
        
        # Generate random
        id_dokter = f"{random.randint(0,9999)}"
        
        # Insert to table dokter
        cursor.execute(f"INSERT INTO medikago.dokter (id_dokter, username, no_sip, spesialisasi) VALUES ('{id_dokter}', '{username}', '{no_sip}', '{spesialisasi}')")
        
        request.session["user"] = "dokter"
        request.session["id"] = id_dokter

        return redirect(reverse("login:pengguna"))
    return redirect(reverse("login:home"))

def signup_pasien(request):
    if(request.method == "GET" and request.session["user"] == "nothing"):   
        signup_pasien = SignUpPasienForm()
        response = {
            'pasien_form': signup_pasien,
        }
        return render(request, 'signup_pasien.html', response)
    elif(request.method == "POST" and request.session["user"] == "nothing"):
        cursor = connection.cursor()
        username = request.POST['username']
        password = request.POST['password']
        nomor_identitas = request.POST['nomor_identitas']
        nama_lengkap = request.POST['nama_lengkap']
        tanggal_lahir = request.POST['tanggal_lahir']
        email = request.POST['email']
        alamat = request.POST['alamat']
        # Insert to table pengguna
        try:
            cursor.execute(f"INSERT INTO medikago.pengguna (email, username, password, nama_lengkap, nomor_id, tanggal_lahir, alamat) VALUES ('{email}','{username}','{password}', '{nama_lengkap}', '{nomor_identitas}','{tanggal_lahir}', '{alamat}')")
        except:
            messages.error(request, "Data yang anda masukkan salah")
            return redirect(reverse("login:signup_pasien"))
        
        # Generate random
        prefix1 = random.randint(100,999)
        prefix2 = random.randint(10,99)
        prefix3 = random.randint(1000,9999)
        no_rekam_medis = f"{prefix1}-{prefix2}-{prefix3}"
        
        # Insert to table pasien
        # Asumsi nama asuransi default Leannon LLC
        cursor.execute(f"INSERT INTO medikago.pasien (no_rekam_medis, username, nama_asuransi) VALUES ('{no_rekam_medis}', '{username}','Leannon LLC')")
        
        request.session["user"] = "pasien"
        request.session["id"] = no_rekam_medis

        return redirect(reverse("login:pengguna"))
    return redirect(reverse("login:home"))


def auth(request):
    if(request.method == "POST" and request.session["user"] == "nothing"):
        cursor = connection.cursor()
        username = request.POST['username']
        password = request.POST['password']
        cursor.execute(f"SELECT * FROM medikago.pengguna where username='{username}' AND password='{password}'")
        select = cursor.fetchone()
        if(select):
            request.session["username"] = username

            cursor.execute(f"SELECT * FROM medikago.administrator where username='{username}'")
            select = cursor.fetchone()
            if(select):
                # select is tuple (nomor_pegawai, username, kode_rs)
                request.session["user"] = "administrator"
                request.session["id"] = select[0]

                return redirect(reverse("login:admin"))
            
            cursor.execute(f"SELECT * FROM medikago.dokter where username='{username}'")
            select = cursor.fetchone()
            if(select):
                # select is tuple (id_dokter, username, no_sip, spesialisasi)
                request.session["user"] = "dokter"
                request.session["id"] = select[0]

                return redirect(reverse("login:pengguna"))
           
            cursor.execute(f"SELECT * FROM medikago.pasien where username='{username}'")
            select = cursor.fetchone()
            if(select):
                # select is tuple (no_rekam_medis, username, nama_asuransi)
                request.session["user"] = "pasien"
                request.session["id"] = select[0]

                return redirect(reverse("login:pengguna"))
            
            return redirect(reverse("login:home"))
            
        
        messages.error(request, "Username atau password yang anda masukkan salah")
        return redirect(reverse("login:home"))

    return redirect(reverse("login:home"))
            
def admin(request):
    if(request.method == "GET" and request.session["user"] == "administrator"):
        return render(request, 'admin.html')
    return redirect(reverse("login:home"))

def pengguna(request):
    if(request.method == "GET" and (request.session["user"] == "dokter" or request.session["user"] == "pasien")):
        return render(request, 'pengguna.html')
    return redirect(reverse("login:home"))

def logout(request):
    if(request.session["user"] != "nothing"):
        messages.success(request, "Anda berhasil keluar dari sistem.")
        request.session.flush()

    return redirect(reverse("login:home"))
    

login/templates/admin.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
Medika Go | Administrator
{% endblock %}

{% block content %}

{% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
{% endif %}

<div class="container">
    <h1 style="color: black;">ADMINISTRATOR</h1>
    
    <a class="btn btn-primary" href="{% url 'app2:profil' %}" style="width: 200px;">
      Profil
    </a>
    <br><br>
    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 200px;">
          Sesi Konsultasi
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'app1:create_sesikonsultasi' %}">Buat Sesi Konsultasi</a>
          <a class="dropdown-item" href="{% url 'app1:daftar_sesikonsultasi' %}">Daftar Sesi Konsultasi</a>
        </div>
      </div>
      <br>
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 200px;">
          Poliklinik
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'app4:create_layanan_poliklinik' %}">Buat Layanan Poliklinik</a>
          <a class="dropdown-item" href="{% url 'app4:daftar_layanan_poliklinik' %}">Daftar Layanan Poliklinik</a>
          <a class="dropdown-item" href="{% url 'app4:create_layanan_poliklinik' %}">Buat Jadwal Poliklinik</a>
          <a class="dropdown-item" href="{% url 'app4:daftar_jadwal_poliklinik' %}">Daftar Jadwal Poliklinik</a>
        </div>
      </div>
      <br>
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 200px;">
          RS Cabang
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'app1:create_rs_cabang' %}">Buat RS Cabang</a>
          <a class="dropdown-item" href="{% url 'app1:daftar_rs_cabang' %}">Daftar RS Cabang</a>
          <a class="dropdown-item" href="{% url 'app4:create_dokter_rs_cabang' %}">Daftarkan Dokter</a>
          <a class="dropdown-item" href="{% url 'app4:daftar_dokter_rs_cabang' %}">Daftar Dokter RS Cabang</a>
          <a class="dropdown-item" href="#">Daftarkan Administrator</a>
        </div>
      </div>
      <br>
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 200px;">
          Tindakan
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'app2:create_tindakan' %}">Buat Tindakan</a>
          <a class="dropdown-item" href="{% url 'app2:view_daftar_tindakan' %}">Daftar Tindakan</a>
          <a class="dropdown-item" href="{% url 'app2:create_tindakan_poli' %}">Buat Tindakan Poliklinik</a>
          <a class="dropdown-item" href="{% url 'app2:view_daftar_tindakan_poli' %}">Daftar Tindakan Poliklinik</a>
        </div>
      </div>
      <br>
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 200px;">
          Resep dan Obat
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="#">Buat Resep</a>
          <a class="dropdown-item" href="#">Daftar Resep</a>
          <a class="dropdown-item" href="#">Buat Obat</a>
          <a class="dropdown-item" href="#">Daftar Obat</a>
        </div>
      </div>
      <br>
      <a class="btn btn-primary" href="{% url 'app5:daftar_transaksi' %}" style="width: 200px;">
        Daftar Transaksi
      </a>
      <br><br>
      <a class="btn btn-danger" href="{% url 'login:logout' %}" style="width: 200px;">
        Logout
      </a>
</div>

{% endblock %}

login/templates/pengguna.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
Medika Go | Pengguna
{% endblock %}

{% block content %}

{% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
{% endif %}

<div class="container">
  <h1 style="color: black;">PENGGUNA</h1>
  
  <a class="btn btn-primary" href="{% url 'app2:profil' %}" style="width: 250px;">
    Profil
  </a>
  <br><br>
  <a class="btn btn-primary" href="{% url 'app1:daftar_sesikonsultasi' %}" style="width: 250px;">
    Daftar Sesi Konsultasi
  </a>
  <br><br>
  <a class="btn btn-primary" href="{% url 'app2:view_daftar_tindakan_poli' %}" style="width: 250px;">
    Daftar Tindakan Poliklinik
  </a>
  <br><br>
  <a class="btn btn-primary" href="{% url 'app2:view_daftar_tindakan' %}" style="width: 250px;">
    Daftar Tindakan
  </a>
  <br><br>
  <a class="btn btn-primary" style="width: 250px;">
    Daftar Resep
  </a>
  <br><br>
  <a class="btn btn-primary" style="width: 250px;">
    Daftar Obat
  </a>
  <br><br>
    <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 250px;">
        RS Cabang
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="{% url 'app1:daftar_rs_cabang' %}">Daftar RS Cabang</a>
        <a class="dropdown-item" href="{% url 'app4:daftar_dokter_rs_cabang' %}">Daftar Dokter RS Cabang</a>
      </div>
    </div>
    <br>
    <a class="btn btn-primary" href="{% url 'app4:daftar_layanan_poliklinik' %}" style="width: 250px;">
      Daftar Layanan
    </a>
    <br><br>
    <a class="btn btn-primary" href="{% url 'app5:daftar_transaksi' %}" style="width: 250px;">
      Daftar Transaksi
    </a>
    <br><br>
    <a class="btn btn-danger" href="{% url 'login:logout' %}" style="width: 250px;">
      Logout
    </a>
</div>

{% endblock %}

login/templates/signup_admin.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
Medika Go | Sign Up Administrator
{% endblock %}

{% block content %}

{% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
{% endif %}
<div class="container">
    <h1 style="color: black;">FORM PENDAFTARAN ADMINISTRATOR</h1>
    <form action="/signup/admin" method="POST" class="form-group">
        {% csrf_token %}
        {% for field in admin_form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="">
            <input type="submit" class="btn btn-primary" value="Daftar Administrator">
        </div>
    </form>
</div>
{% endblock %}

login/templates/signup_dokter.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
Medika Go | Sign Up Dokter
{% endblock %}

{% block content %}

{% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
{% endif %}
<div class="container">
    <h1 style="color: black;">FORM PENDAFTARAN DOKTER</h1>
    <form action="/signup/dokter" method="POST" class="form-group">
        {% csrf_token %}
        {% for field in dokter_form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="">
            <input type="submit" class="btn btn-primary" value="Daftar Dokter">
        </div>
    </form>
</div>
{% endblock %}

login/templates/signup_pasien.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
Medika Go | Sign Up Pasien
{% endblock %}

{% block content %}

{% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
{% endif %}
<div class="container">
    <h1 style="color: black;">FORM PENDAFTARAN PASIEN</h1>
    <form action="/signup/pasien" method="POST" class="form-group">
        {% csrf_token %}
        {% for field in pasien_form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="">
            <input type="submit" class="btn btn-primary" value="Daftar Pasien">
        </div>
    </form>
</div>
{% endblock %}