app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'
urlpatterns = [
    path('', views.create_sesikonsultasi, name='create_sesikonsultasi'),
    path('daftar_sesi_konsultasi', views.daftar_sesikonsultasi, name='daftar_sesikonsultasi'),
    path('update_sesi_konsultasi', views.update_sesikonsultasi, name='update_sesikonsultasi'),
    path('delete_sesi_konsultasi', views.delete_sesikonsultasi, name='delete_sesikonsultasi'),
    path('create_rs_cabang',views.create_rs_cabang, name='create_rs_cabang'),
    path('daftar_rs_cabang', views.daftar_rs_cabang, name='daftar_rs_cabang'),
    path('update_rs_cabang', views.update_rs_cabang, name='update_rs_cabang'),
    path('delete_rs_cabang', views.delete_rs_cabang, name= 'delete_rs_cabang'),
]

app4/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from .views import *
from . import views

app_name = 'app4'

urlpatterns = [
    path('create_dokter_rs_cabang', create_dokter_rs_cabang, name='create_dokter_rs_cabang'),
    path('daftar_dokter_rs_cabang', daftar_dokter_rs_cabang, name='daftar_dokter_rs_cabang'),
    path('update_dokter_rs_cabang', update_dokter_rs_cabang, name='update_dokter_rs_cabang'),
    path('delete_dokter_rs_cabang', delete_dokter_rs_cabang, name='delete_dokter_rs_cabang'),

    path('create_layanan_poliklinik', create_layanan_poliklinik, name='create_layanan_poliklinik'),
    path('daftar_layanan_poliklinik', daftar_layanan_poliklinik, name='daftar_layanan_poliklinik'),
    path('update_layanan_poliklinik/<id>/', update_layanan_poliklinik, name='update_layanan_poliklinik'),
    path('delete_layanan_poliklinik/<id>/', delete_layanan_poliklinik, name='delete_layanan_poliklinik'),

    path('daftar_jadwal_poliklinik', daftar_jadwal_poliklinik, name='daftar_jadwal_poliklinik'),
    path('daftar_jadwal_poliklinik/<id>/', daftar_jadwal_poliklinik_khusus, name='daftar_jadwal_poliklinik'),
    path('update_jadwal_poliklinik/<id>/', update_jadwal_poliklinik, name='update_jadwal_poliklinik'),
    path('delete_jadwal_poliklinik/<id>/', delete_jadwal_poliklinik, name='delete_jadwal_poliklinik'),

]

medikago_b5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
    path('app4/', include('app4.urls')),
    path('app5/', include('app5.urls')),
]

app4/models.py
from django.db import models

# Create your models here.
class dokterModel(models.Model):
    idDokter = models.CharField(max_length = 7, choices = [('1', '1'), ('2','2'),('3','3'), ('4','4'), ('5','5'), ('6', '6'), ('7','7')])
    kodeRS = models.CharField(max_length = 12, choices = [('1', '1'), ('2','2'),('3','3'), ('4','4'), ('5','5'), ('6', '6'), ('7','7'),('8','8'), ('9','9'), ('10','10'), ('11', '11'), ('12','12')])

app4/forms.py
from django import forms
from django.db import connection

cursor = connection.cursor()
cursor.execute("SELECT id_dokter FROM medikago.dokter order by id_dokter")
select = cursor.fetchall()
cursor.execute("SELECT kode_rs FROM medikago.rs_cabang order by kode_rs")
select2 = cursor.fetchall()

id_dokter_choices = [tuple([select[x][0], select[x][0]]) for x in range(len(select))]
Kode_RS_choices = [tuple([select2[x][0],select2[x][0]]) for x in range(len(select2))]


# Tindakan Poliklinik

class CreateDaftarDokterForm(forms.Form):
    id_dokter = forms.CharField(label="ID Dokter", widget=forms.Select(choices=id_dokter_choices, attrs={
        'class': 'form-control'
    }))

    kode_rs = forms.CharField(label="Kode RS", widget=forms.Select(choices=Kode_RS_choices, attrs={
        'class': 'form-control'
    }))

class CreatePoliklinikForm(forms.Form):

    nama_layanan = forms.CharField(label='Nama Layanan', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'required': True}) )
    deskripsi = forms.CharField(label='Deskripsi', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'required': True}))
    kode_rs_cabang = forms.CharField(label="Kode RS", widget=forms.Select(choices=Kode_RS_choices, attrs={
        'class': 'form-control'
    }))
    hari = forms.CharField(label='Hari', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'required': True}))
    mulai = forms.CharField(label='Waktu Mulai', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'required': True}))
    selesai = forms.CharField(label='Waktu Selesai', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'required': True}))
    kapasitas = forms.CharField(label='Kapasitas', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'required': True}))

app4/views.py
from django.shortcuts import render, redirect, reverse
from .forms import *
from django.db import connection
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
import datetime
from collections import namedtuple


# Create your views here.

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def create_dokter_rs_cabang(request):
    if(request.method == "GET" and request.session["user"] == "administrator"):
        create_dokter_rs_cabang = CreateDaftarDokterForm()
        response = {'create_form_daftar_dokter': create_dokter_rs_cabang}
        return render(request, 'create_dokter_rs_cabang.html', response)
    elif(request.method == "POST" and request.session["user"] == "administrator"):
        cursor = connection.cursor()
        id_dokter = request.POST["id_dokter"]
        kode_rs = request.POST["kode_rs"]
        try:
            cursor.execute(f"INSERT INTO medikago.dokter_rs_cabang VALUES ('{id_dokter}','{kode_rs}')")
            messages.info(request,"Dokter RS Cabang Berhasil di Tambahkan")
        except:
            messages.error(request,"Create RS Cabang gagal !! terdapat kesamaan pada Kode RS, Coba Ulangi Lagi")
            return redirect(reverse("app4:create_dokter_rs_cabang"))
        # print(request.POST)
        return redirect(reverse("app4:daftar_dokter_rs_cabang"))
    return redirect(reverse("login:pengguna"))

def daftar_dokter_rs_cabang(request):
    response = {}
    data_dokter_rs_cabang = []
    cursor = connection.cursor()
    if(request.method == "GET" and request.session["user"] != "nothing"):
        cursor.execute(f"SELECT kode_rs,id_dokter FROM medikago.dokter_rs_cabang ORDER BY kode_rs")
        data = cursor.fetchall()
        for i in data:
            data_dokter_rs_cabang.append({
                "id_dokter" : f"{i[1]}",
                "kode_rs" : f"{i[0]}"
            })
        response = {'daftar_dokter_rs_cabang': data_dokter_rs_cabang}
        # print(data)
        return render(request, 'daftar_dokter_rs_cabang.html',response)
    return redirect(reverse("login:home"))


def update_dokter_rs_cabang(request):
    response = {}
    cursor = connection.cursor()
    if(request.method == "GET" and request.session["user"] == "administrator"):
        try:
            if(request.GET['kode_rs'] and request.GET['id_dokter'] ):
                pass
        except:
            return redirect(reverse("app4:daftar_dokter_rs_cabang"))

        response["kode_rs"] = request.GET['kode_rs']
        response["id_dokter"] = request.GET['id_dokter']

        cursor.execute("SELECT id_dokter FROM medikago.dokter order by id_dokter")
        select = cursor.fetchall()
        cursor.execute("SELECT kode_rs FROM medikago.rs_cabang order by kode_rs")
        select2 = cursor.fetchall()

        response["id_dokter_choices"] = [select[x][0] for x in range(len(select))]
        response["kode_rs_choices"] = [select2[x][0] for x in range(len(select2))]

        return render(request,'update_dokter_rs_cabang.html',response)
        
    elif(request.method == "POST" and request.session["user"] == "administrator"):
        cursor = connection.cursor()
        id_dokter = request.POST["id_dokter"]
        kode_rs = request.POST["kode_rs"]
        id_dokter_new = request.POST["id_dokter_new"]
        kode_rs_new = request.POST["kode_rs_new"]

        try:
            cursor.execute(f"UPDATE medikago.dokter_rs_cabang SET id_dokter = '{id_dokter_new}',kode_rs = '{kode_rs_new}' where id_dokter = '{id_dokter}' AND kode_rs = '{kode_rs}'")
            messages.info(request,"Update Dokter RS Cabang Berhasil")
        except:
            messages.error(request,"Update dokter rs cabang gagal, coba ulangi lagi")
            return redirect(reverse("app4:update_dokter_rs_cabang"))
        return redirect(reverse("app4:daftar_dokter_rs_cabang"))
    return redirect(reverse("login:pengguna"))


def delete_dokter_rs_cabang(request):
    if (request.method == 'GET' and request.session["user"] == 'administrator'):
        cursor = connection.cursor()
        try:
            if(request.GET["id_dokter"] and request.GET["kode_rs"]):
                id_dokter = request.GET["id_dokter"]
                kode_rs = request.GET["kode_rs"]
                cursor.execute(f"DELETE FROM medikago.dokter_rs_cabang WHERE kode_rs = '{kode_rs}' AND id_dokter = '{id_dokter}'")
                messages.info(request,"Delete Dokter RS Cabang Berhasil")
                return redirect(reverse('app4:update_dokter_rs_cabang'))
        except:
            messages.error(request,"Delete dokter rs cabang gagal, coba ulangi lagi")
            return redirect(reverse('app4:update_dokter_rs_cabang'))

        return redirect(reverse('app4:update_dokter_rs_cabang'))


def create_layanan_poliklinik(request):
    if(request.method == "GET" and request.session["user"] == "administrator"):
        create_layanan_poliklinik = CreatePoliklinikForm()
        response = {'create_layanan_poliklinik': create_layanan_poliklinik}
        return render(request, 'create_layanan_poliklinik.html', response)
    elif(request.method == "POST" and request.session["user"] == "administrator"):
        cursor = connection.cursor()
        cursor.execute("SELECT id_poliklinik FROM medikago.layanan_poliklinik ORDER BY id_poliklinik DESC LIMIT 1")

        id_poliklinik = cursor.fetchone()[0].split("-")
        id_poliklinik[-1] = str(int(id_poliklinik[-1]) + 1)
        id_poliklinik = "-".join(id_poliklinik)

        nama = request.POST["nama_layanan"]
        deskripsi = request.POST["deskripsi"]
        kode_rs_cabang = request.POST["kode_rs_cabang"]


        cursor.execute("SELECT id_jadwal_poliklinik FROM medikago.jadwal_layanan_poliklinik ORDER BY id_jadwal_poliklinik DESC LIMIT 1")

        id_jadwal_poliklinik = cursor.fetchone()[0].split("-")
        id_jadwal_poliklinik[-1] = str(int(id_jadwal_poliklinik[-1]) + 1)
        id_jadwal_poliklinik = "-".join(id_jadwal_poliklinik)
        id_dokter = 1
        hari = request.POST["hari"]
        waktu_mulai = request.POST["mulai"]
        waktu_selesai = request.POST["selesai"]
        kapasitas = request.POST["kapasitas"]
        try:
            cursor.execute(f"INSERT INTO medikago.layanan_poliklinik VALUES ('{id_poliklinik}','{kode_rs_cabang}', '{nama}','{deskripsi}')")
            cursor.execute(f"INSERT INTO medikago.jadwal_layanan_poliklinik VALUES ('{id_jadwal_poliklinik}','{waktu_mulai}', '{waktu_selesai}','{hari}',{kapasitas},'{id_dokter}','{id_poliklinik}' )")
        except:

            return redirect(reverse("app4:create_layanan_poliklinik"))
        # print(request.POST)
        return redirect(reverse("app4:daftar_layanan_poliklinik"))
    return redirect(reverse("login:pengguna"))



def daftar_layanan_poliklinik(request):
    response = {}
    data_daftar_layanan_poli = []
    cursor = connection.cursor()
    if(request.method == "GET" and request.session["user"] != "nothing"):
        cursor.execute(f"SELECT * FROM medikago.layanan_poliklinik ORDER BY id_poliklinik")
        data = cursor.fetchall()
        for i in data:
            data_daftar_layanan_poli.append({
                "id_poliklinik" : f"{i[0]}",
                "kode_rs_cabang" : f"{i[1]}",
                "nama" : f"{i[2]}",
                "deskripsi" : f"{i[3]}"
            })
        response['table'] = data_daftar_layanan_poli

        return render(request, 'daftar_layanan_poliklinik.html',response)
    return redirect(reverse("login:home"))




def update_layanan_poliklinik(request, id):
    response = {}
    cursor = connection.cursor()
    if(request.method == "GET" and request.session["user"] == "administrator"):
        
        cursor.execute(f"SELECT * FROM medikago.layanan_poliklinik WHERE id_poliklinik = '{id}'")
        select = cursor.fetchone()
        if(select):
            data = {
                "id_poliklinik": f"{select[0]}",
                "kode_rs_cabang": f"{select[1]}",
                "nama": f"{select[2]}",
                "deskripsi" : f"{select[3]}"
            }
        else:
            return redirect(reverse("app4:daftar_layanan_poliklinik"))
        response['data_update'] = data


        cursor.execute("SELECT kode_rs FROM medikago.rs_cabang order by kode_rs")
        select2 = cursor.fetchall()
        response["kode_rs_choices"] = [select2[x][0] for x in range(len(select2))]

        
        return render(request,'update_layanan_poliklinik.html', response)
        
    elif(request.method == "POST" and request.session["user"] == "administrator"):
        cursor = connection.cursor()
        nama = request.POST["nama_layanan"]
        deskripsi = request.POST["deskripsi"]
        kode_rs_cabang = request.POST["kode_rs_cabang"]
        try:
            cursor.execute(f"UPDATE medikago.layanan_poliklinik SET nama = '{nama}', deskripsi = '{deskripsi}', kode_rs_cabang = '{kode_rs_cabang}' WHERE id_poliklinik = '{id}'")
            # messages.info(request,"Update Layanan Poliklinik Berhasil")
        except:
            # messages.error(request,"Update layanan poliklinik gagal, coba ulangi lagi")
            return redirect(reverse("app4:update_layanan_poliklinik"))
        return redirect(reverse("app4:daftar_layanan_poliklinik"))
    return redirect(reverse("login:pengguna"))


def delete_layanan_poliklinik(request, id):
    if (request.method == 'GET' and request.session["user"] == 'administrator'):
        cursor = connection.cursor()
        delete_layanan = "delete from medikago.layanan_poliklinik where id_poliklinik = '" + id + "'"
        cursor.execute(delete_layanan)
        return redirect(reverse('app4:daftar_layanan_poliklinik'))



def daftar_jadwal_poliklinik_khusus(request, id):
    response = {}
    data_jadwal = []
    cursor = connection.cursor()

app4/templates/create_dokter_rs_cabang.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
Daftar Dokter
{% endblock %}

{% block content %}

{% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
{% endif %}
<div class="container">
    <h1 style="color: black;">FORM DAFTAR DOKTER</h1>
    <form action="create_dokter_rs_cabang" method="POST" class="form-group">
        {% csrf_token %}
        {% for field in create_form_daftar_dokter %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="">
            <input type="submit" class="btn btn-primary" value="Submit">
        </div>
    </form>
</div>
{% endblock %}

app4/templates/create_layanan_poliklinik.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
Pembuatan Layanan Poliklinik
{% endblock %}

{% block content %}

{% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
{% endif %}
<div class="container">
    <h1 style="color: black;">FORM LAYANAN POLIKLINIK</h1>
    <form action="create_layanan_poliklinik" method="POST" class="form-group">
        {% csrf_token %}
        {% for field in create_layanan_poliklinik %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Create Layanan Poliklinik">
  
    </form>
</div>
{% endblock %}

app4/templates/daftar_jadwal_poliklinik.html
<!-- <!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2>HTML Table</h2>

<table>
    <tr>
        <th>ID Jadwal Poliklinik</th>
        <th>Hari</th>
        <th>Waktu Mulai</th>
        <th>Waktu Selesai</th>
        <th>Kapasitas</th>
        <th>ID Dokter</th>
        <th>ID Poliklinik</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>891-18-0799</th>
        <th>Senin</th>
        <th>8:00:00 AM</th>
        <th>5:00:00 PM</th>
        <th>6</th>
        <th>3</th>
        <th>67510-0082</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>184-74-7068</th>
        <th>Selasa</th>
        <th>9:00:00 AM</th>
        <th>4:30:00 PM</th>
        <th>6</th>
        <th>4</th>
        <th>41163-300</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>588-54-3944</th>
        <th>Rabu</th>
        <th>8:30:00 AM</th>
        <th>6:00:00 PM</th>
        <th>4</th>
        <th>5</th>
        <th>67510-0082</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>586-61-0853</th>
        <th>Kamis</th>
        <th>8:30:00 AM</th>
        <th>6:30:00 PM</th>
        <th>4</th>
        <th>1</th>
        <th>67510-0082</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>812-04-9571</th>
        <th>Jumat</th>
        <th>9:00:00 AM</th>
        <th>6:30:00 PM</th>
        <th>6</th>
        <th>7</th>
        <th>67510-0082</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>731-16-2267</th>
        <th>Sabtu</th>
        <th>9:00:00 AM</th>
        <th>5:00:00 PM</th>
        <th>3</th>
        <th>5</th>
        <th>41163-300</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>404-39-2659</th>
        <th>Senin</th>
        <th>9:00:00 AM</th>
        <th>6:00:00 PM</th>
        <th>3</th>
        <th>7</th>
        <th>55441-901</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>110-86-0330</th>
        <th>Selasa</th>
        <th>9:00:00 AM</th>
        <th>4:30:00 PM</th>
        <th>3</th>
        <th>1</th>
        <th>50845-0109</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>189-24-8568</th>
        <th>Rabu</th>
        <th>9:00:00 AM</th>
        <th>6:00:00 PM</th>
        <th>6</th>
        <th>7</th>
        <th>50845-0109</th>
        <th>Action [admin]</th>
      </tr>
      <tr>
        <th>162-33-6962</th>
        <th>Kamis</th>
        <th>9:00:00 AM</th>
        <th>5:00:00 PM</th>
        <th>3</th>
        <th>2</th>
        <th>41163-300</th>
        <th>Action [admin]</th>
      </tr>
</table>
</body>
</html> -->



<!-- -->


<!-- <!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2>Daftar Dokter RS Cabang</h2>

<table>
  <tr>
    <th>ID Layanan Poliklinik</th>
    <th>Nama</th>
    <th>Deskripsi</th>
    <th>Kode RS Cabang</th>
    <th>Jadwal Poliklinik</th>
    <th>Action[admin]</th>
  </tr>
  <tr>
    <td>41163-300</td>
    <td>AINI Eye Hospital</td>
    <td>Eye Doctor</td>
    <td>23-895-1256</td>
    <td><a href="jadwal"><button class="btn btn-outline-primary">Jadwal</button></a></td>
    <td><a href="update_jadwal_poliklinik"><button class="btn btn-outline-primary">Update</button></a>
        <a href="daftar_dokter_rs_cab"><button class="btn btn-outline-primary">Delete</button></a></td>
  </tr>
  <tr>
    <td>14783-045</td>
    <td>Morula IVF</td>
    <td>IVF Clinic</td>
    <td>67-764-0411 </td>
    <td><a href="jadwal"><button class="btn btn-outline-primary">Jadwal</button></a></td>
    <td><a href="update_jadwal_poliklinik"><button class="btn btn-outline-primary">Update</button></a>
        <a href="daftar_dokter_rs_cab"><button class="btn btn-outline-primary">Delete</button></a></td>
  </tr>
  <tr>
    <td>50845-0109</td>
    <td>Dharmain Cancer Hospital</td>
    <td>Specialist in Cancer</td>
    <td>23-895-1256</td>
    <td><a href="jadwal"><button class="btn btn-outline-primary">Jadwal</button></a></td>
    <td><a href="update_jadwal_poliklinik"><button class="btn btn-outline-primary">Update</button></a>
        <a href="daftar_dokter_rs_cab"><button class="btn btn-outline-primary">Delete</button></a></td>
  </tr>
  <tr>
    <td>67510-0082</td>
    <td>Dharmatologist</td>
    <td>UK</td>
    <td>23-895-1256</td>
    <td><a href="jadwal"><button class="btn btn-outline-primary">Jadwal</button></a></td>
    <td><a href="update_jadwal_poliklinik"><button class="btn btn-outline-primary">Update</button></a>
        <a href="daftar_dokter_rs_cab"><button class="btn btn-outline-primary">Delete</button></a></td>
  </tr>
  <tr>
    <td>55441-901</td>
    <td>PROSTASIA</td>
    <td>Clinic for vaccine</td>
    <td>23-895-1256</td>
    <td><a href="jadwal"><button class="btn btn-outline-primary">Jadwal</button></a></td>
    <td><a href="update_jadwal_poliklinik"><button class="btn btn-outline-primary">Update</button></a>
        <a href="daftar_dokter_rs_cab"><button class="btn btn-outline-primary">Delete</button></a></td>
  </tr>
</table>

</body>
</html> -->



{% extends 'base.html' %}
{% load static %}

{% block subtitle %}
Jadwal Poliklinik
{% endblock %}

{% block content %}

{% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
{% endif %}
  <div class="container">
    <div class="page-header">
        <h1>Informasi Jadwal Layanan Poliklinik</h1>
    </div>
    <div>
        <table class=' table table-condensed '>
            <thead>
                <tr>
                    <th>ID Jadwal Poliklinik</th>
                    <th>Hari</th>
                    <th>Waktu Mulai</th>
                    <th>Waktu Selesai</th>
                    <th>Kapasitas</th>
                    <th>ID Dokter</th>
                    <th>ID Poliklinik</th>
                    {% if request.session.user == "administrator" %}
                        <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for data in jadwal %}
                <tr>
                    {% if request.session.user == "administrator" %}
                    
                    {% endif %}
                        <td>{{data.id_jadwal_poliklinik}}</td>
                        <td>{{data.hari}}</td>
                        <td>{{data.waktu_mulai}}</td>
                        <td>{{data.waktu_selesai}}</td>
                        <td>{{data.kapasitas}}</td>
                        <td>{{data.id_dokter}}</td>
                        <td>{{data.id_poliklinik}}</td>                   
                        {% if request.session.user == "administrator" %}
                        <td>
                            
                                <div class="pi-draggable btn-group" draggable="true">
                                    
                                  <a class="btn btn-primary" href="{% url 'app4:update_jadwal_poliklinik' data.id_jadwal_poliklinik %}">Update</a>
                                    

                                  <a class="btn btn-danger" href="{% url 'app4:delete_jadwal_poliklinik' data.id_jadwal_poliklinik %}">Delete</a>
                                    
                                </div>
                                
                            </form>
                        </td>
                        
                        {% endif %}
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
{% endblock %}